export type Language = "English" | "हिंदी" | "ಕನ್ನಡ" | "తెలుగు" | "தமிழ்" | "मराठी" | "বাংলা";

type Copy = { farmer: string; procurement: string; name: string; phone: string; aadhaar: string; pan: string; loginFarmer: string; loginProcurement: string; continueFarmer: string; continueProcurement: string; welcome: string; language: string; voice: string; identityNote: string };

const english: Copy = { farmer: "Farmer", procurement: "Procurement staff", name: "Full name", phone: "Mobile number", aadhaar: "Aadhaar number", pan: "PAN card number", loginFarmer: "Farmer login", loginProcurement: "Procurement login", continueFarmer: "Continue to farmer desk", continueProcurement: "Open operations desk", welcome: "Welcome to KrishiGati", language: "Language", voice: "Voice help", identityNote: "Your identity information is transmitted securely." };

export const copy: Record<string, Copy> = {
  English: english,
  "हिंदी": { farmer: "किसान", procurement: "खरीद केंद्र कर्मचारी", name: "पूरा नाम", phone: "मोबाइल नंबर", aadhaar: "आधार नंबर", pan: "पैन कार्ड नंबर", loginFarmer: "किसान लॉगिन", loginProcurement: "खरीद केंद्र लॉगिन", continueFarmer: "किसान डेस्क खोलें", continueProcurement: "ऑपरेशंस डेस्क खोलें", welcome: "कृषिगति में आपका स्वागत है", language: "भाषा", voice: "आवाज़ सहायता", identityNote: "आपकी पहचान की जानकारी सुरक्षित रूप से भेजी जाती है।" },
  "ಕನ್ನಡ": { farmer: "ರೈತ", procurement: "ಖರೀದಿ ಕೇಂದ್ರ ಸಿಬ್ಬಂದಿ", name: "ಪೂರ್ಣ ಹೆಸರು", phone: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ", aadhaar: "ಆಧಾರ್ ಸಂಖ್ಯೆ", pan: "ಪ್ಯಾನ್ ಕಾರ್ಡ್ ಸಂಖ್ಯೆ", loginFarmer: "ರೈತ ಲಾಗಿನ್", loginProcurement: "ಖರೀದಿ ಲಾಗಿನ್", continueFarmer: "ರೈತ ಡೆಸ್ಕ್ ತೆರೆಯಿರಿ", continueProcurement: "ಕಾರ್ಯಾಚರಣೆ ಡೆಸ್ಕ್ ತೆರೆಯಿರಿ", welcome: "ಕೃಷಿಗತಿಗೆ ಸ್ವಾಗತ", language: "ಭಾಷೆ", voice: "ಧ್ವನಿ ಸಹಾಯ", identityNote: "ನಿಮ್ಮ ಗುರುತಿನ ಮಾಹಿತಿ ಸುರಕ್ಷಿತವಾಗಿ ಕಳುಹಿಸಲಾಗುತ್ತದೆ." },
  "తెలుగు": { farmer: "రైతు", procurement: "కొనుగోలు కేంద్ర సిబ్బంది", name: "పూర్తి పేరు", phone: "మొబైల్ నంబర్", aadhaar: "ఆధార్ నంబర్", pan: "పాన్ కార్డ్ నంబర్", loginFarmer: "రైతు లాగిన్", loginProcurement: "కొనుగోలు లాగిన్", continueFarmer: "రైతు డెస్క్ తెరవండి", continueProcurement: "ఆపరేషన్స్ డెస్క్ తెరవండి", welcome: "కృషిగతికి స్వాగతం", language: "భాష", voice: "వాయిస్ సహాయం", identityNote: "మీ గుర్తింపు సమాచారం సురక్షితంగా పంపబడుతుంది." },
  "தமிழ்": { farmer: "விவசாயி", procurement: "கொள்முதல் மைய பணியாளர்", name: "முழு பெயர்", phone: "மொபைல் எண்", aadhaar: "ஆதார் எண்", pan: "பான் அட்டை எண்", loginFarmer: "விவசாயி உள்நுழைவு", loginProcurement: "கொள்முதல் உள்நுழைவு", continueFarmer: "விவசாயி டெஸ்க்கைத் திறக்கவும்", continueProcurement: "செயல்பாட்டு டெஸ்க்கைத் திறக்கவும்", welcome: "கிருஷிகதிக்கு வரவேற்கிறோம்", language: "மொழி", voice: "குரல் உதவி", identityNote: "உங்கள் அடையாள தகவல் பாதுகாப்பாக அனுப்பப்படும்." },
  "मराठी": { farmer: "शेतकरी", procurement: "खरेदी केंद्र कर्मचारी", name: "पूर्ण नाव", phone: "मोबाईल क्रमांक", aadhaar: "आधार क्रमांक", pan: "पॅन कार्ड क्रमांक", loginFarmer: "शेतकरी लॉगिन", loginProcurement: "खरेदी लॉगिन", continueFarmer: "शेतकरी डेस्क उघडा", continueProcurement: "ऑपरेशन्स डेस्क उघडा", welcome: "कृषिगतीमध्ये स्वागत आहे", language: "भाषा", voice: "आवाज मदत", identityNote: "तुमची ओळख माहिती सुरक्षितपणे पाठवली जाते." },
  "বাংলা": { farmer: "কৃষক", procurement: "ক্রয় কেন্দ্র কর্মী", name: "পুরো নাম", phone: "মোবাইল নম্বর", aadhaar: "আধার নম্বর", pan: "প্যান কার্ড নম্বর", loginFarmer: "কৃষক লগইন", loginProcurement: "ক্রয় লগইন", continueFarmer: "কৃষক ডেস্ক খুলুন", continueProcurement: "অপারেশন ডেস্ক খুলুন", welcome: "কৃষিগতিতে স্বাগতম", language: "ভাষা", voice: "ভয়েস সহায়তা", identityNote: "আপনার পরিচয় তথ্য নিরাপদে পাঠানো হয়।" },
};

export function getCopy(language: string) { return copy[language] || english; }
